neocities/neocities

- public/gateway_error.html
- views/_footer.erb
- views/_team.erb
- views/templates/email/supporter_upgrade.erb
- views/templates/email_subscription.erb
- views/templates/email_welcome.erb
Neocities recently went from @NeocitiesWeb to @Neocities on Twitter, so Neocities.org should reflect that.
> Change all Twitter links to @Neocities from @NeocitiesWeb

- views/browse.erb
Fixed title ignoring surf mode state and leading to the wrong page if
the current page is >1
(And also removed double `href` attribute when surfmode isn't enabled)
> Fixed browsing tiles leading to unintended pages

- models/site.rb
Underscores are not allowed in usernames, so they shouldn't be mentioned as allowed.
Resubmitting this as the previous pull request was incorrect, apologies for that.
> Remove Mention of Underscores in Signup Dialog

- README.md
- vagrant/development.sh
- `cd /vagrant` is done automatically now on login to the `vagrant` user.
- The `disposable_email_blacklist.conf` file is now generated automatically if it does not exist.
This one I added it automatically because is a pain, but if you don't want it to create like this I will change the README to specify that this file needs to be created (rather to get an error on the first run and figuring out what's happening!).
> Added two little details to Vagrant environment

- views/site_files/mount_info.erb
Updated the webdav documentation styles a bit and added a section explaining how to connect to other sites than the parent one.
**Edit** Just saw #294. Updated the link here as well.
As a question, I used [here](https://github.com/neocities/neocities/pull/299/files#diff-fe0dea6bcf4418fa3db8364df22af4cfR72) an absolute path to link to an URL. Is there a way to do reverse URLs without manually writing it in RoR?
> Updated WebDAV documentation

- README.md
The fork button at the top of github is https://github.com/OWNER/REPO/fork. 
Using this link makes it slightly easier for newer contributors to do the right thing
> docs(readme): use github fork link

- views/_share.erb
They are all very dead & show no signs of returning any time soon, sadly.
> Remove dead social networks from share button

- views/tutorials.erb
Fixes #419 I guess.
Note that we might want to also remove TeamTreehouse and change the link for Codecademy,
[as I commented at that issue](https://github.com/neocities/neocities/issues/419#issuecomment-1417701083),
as TeamTreehouse requires a credit card for a 7 day free trial, and the codecademy Web Development Catalog includes a lot of overwhelming backend courses (we can link directly to the HTML course instead)
> Cleanup Tutorials page links

- Vagrantfile
- vagrant/development.sh
- vagrant/ruby.sh
In particular this fixes some Chrome test failures. The old version of Chromium available on Trusty was giving JavaScript errors.
RAM had to be increased too, because Git was running out of memory during provisioning.
Also upgrade to Ruby 2.6 to fix dependencies.
Skip Ubuntu 16.04 Xenial because it is close to end-of-life. For example being [removed from GitHub Actions](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/) soon.
> Upgrade Vagrant to bionic (was trusty)

- views/_share.erb
This PR fixes two small issues with the Mastodon share link:
1. Mastodon was not given a new line unlike all the other share links, so it was showing up right next to Tumblr.
2. The code that generated query params seems to have been copied from Tumblr or Facebook and it does not fill in the textbox correctly. Fix this so the prefilled "Toot" matches what Twitter share would post.
> Fix Mastodon Share

- Vagrantfile
Was working trying to get a dev environment set up via the readme.
There are quite a few dependencies in the 18.04 LTS repos that are out of date and cause a bundle install to fail for whatever reason. I think the default version of bundler in 18.04 is still major version 1 for example. There was a myriad of issues basically.
Updating to 22.04 went a long way in making sure I can apt install the correct dependencies, such as Ruby 3 etc. This isn't a comprehensive fix to several issues I encountered while trying to get the dev environment working (why work on improving the dev environment with limited time on a free site?), but I think this is a low hanging fruit that would hopefully make it less painful for people. Although it was still a minor trial by fire for me and I'm a better …
> Update Vagrant to latest Ubuntu LTS

- sass/_project-sass/_project-Main.scss
- views/site.erb
This change improves stat display counters for small screens.
I tested with some ridiculous values and compared between my revision and the live site. This was at a resolution of 375px wide. 1 billion views, 20,000 followers, 100,000 updates. First is live site, then my revision.
Not perfect, but there's no overlapping text. I tried to keep the single row thing and keep it faithful to the original design.
Here are some more realistic large numbers: 1 million views, no followers (😥) and 100,000 updates. First is live site, then my revision.
Whether this change is merged will probably depend on the philosophy of the site. I think this is the first display: flex used across the entire codebase. So I'm not sure if the philosophy is to support old browsers as much as possible, or whether (I …
> Improve responsiveness for mobile screens for sites with large site stats

- sass/_project-sass/_project-Main.scss
> I made a fix to prevent large portrait images from overflowing on certain resolutions

- sass/_project-sass/_project-Main.scss
The original text color didn't pass any of the WCAG tests:
This means that users with low vision won't be able to read the text in the tags very easily.
Using the luminance slider, I darkened the text color until it passed nearly all of the WCAG tests and most importantly the WCAG AA Normal Text test. I didn't darken it too much since I wanted to maintain a balance between aesthetics and function. Below are the the results:
> I made the site tag text color darker so it passes most WCAG accessibility standards.

- sass/_project-sass/_project-Main.scss
A small fix to make the position of avatars consistent.
Before:
After:
> Fix avatar positioning

- views/_follows.erb
"see more" link on follows shows incorrect link (goes to followers instead of follows)
This PR fixes this
> Fix follows' "see more" link

- app/api.rb
- models/site_file.rb
Purpose of this PR:
- ext4 filesystems permit a filename limit of 255 characters
- changes arbitrary 100-character limit to the above limit
- many site builders will create minified files with names over 100 characters in length
- adds the limit as part of the error return as well
- this is hard-coded currently (I am not intimately familiar with ruby)
relates to issue #498
> Bug: Filename Length

- workers/lets_encrypt_worker.rb
The .well-known directory has uses other than ACME challenge response, so deleting the whole thing as cleanup is incorrect.
I ran into an issue where files I uploaded inside that directory (which worked initially) disappeared after a while, I assume around the time neocities renewed the certs for my custom domain and this cleanup code ran. The file (and the .well-known dir) still appeared in GETs on the /api/list endpoint, but requests for them on my site returned 404. I tried to re-upload the original to the same path but it appears since it had the same content some optimization was preventing it from restoring the deleted file, because it continued to 404.
Uploading the same file to a different path inside .well-known worked, and then uploading a file with different content to the …
> Make ACME challenge cleanup more specific

- views/tutorials.erb
There was an *extremely* small typo on the “learn” page, and I fixed it.
> Fix “ungird” typo

- models/site.rb
This PR adds the `.rss` extension to the `VALID_EDITABLE_EXTENSIONS` array, allowing users to edit their RSS files directly through the Neocities web interface. While RSS files are allowed to be hosted on Neocities (`application/rss+xml` in `VALID_MIME_TYPES`), users cannot edit them through the interface and must re-upload them each time they want to make changes.
Since RSS files are already allowed to be hosted, are text-based XML files (which are already editable), and are safe to edit through a web interface, I think this change will improve the user experience with no negative effect on security
Fixes #570
> Add rss to valid editable file extensions
